@extends('master')
@section('content')
    @include('pages.homepage.partials.banner')
    @include('pages.homepage.partials.about')
    @include('pages.homepage.partials.treatments')
    @include('pages.homepage.partials.procedures')
    @include('pages.homepage.partials.testimonials')
    @include('pages.homepage.partials.team')
@endsection
